apiVersion: v1
kind: Namespace
metadata:
  name: production
  labels:
    name: production
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webpage-deployment
  namespace: production
spec:
  replicas: 2
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      application: webpage
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 30
  template:
    metadata:
      name: webpage-pod
      labels:
        application: webpage
    spec:
      containers:
      - name: webpage-container
        image: 952149495092.dkr.ecr.ap-south-1.amazonaws.com/maventestproject:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: ecr-secret  
---
apiVersion: v1
kind: Service
metadata:
  name: webpage-service
  namespace: production
spec:
  type: NodePort
  selector:
    application: webpage
  ports:
  - port: 80
    targetPort: 8080